language: rust
env:
- zipname="hardback-$TRAVIS_OS_NAME.tar.gz"
cache: cargo
rust:
- stable
os:
- linux
- osx
sudo: false
script:
- cargo build --release
matrix:
  allow_failures:
  - os: osx
before_deploy:
- tar -zcvf $zipname target
addons:
  apt:
    packages:
    - libasound2-dev
deploy:
  provider: s3
  access_key_id: AKIAJYTGSC6HEOD2PLEQ
  secret_access_key:
    secure: ZQY6qpOEW00LM/Bq0sSXOgh4puEefZR4MnOGBIQJqVq8xgi4iDbamfMknMaJIw3CKN0LsxxjVMtIMR4vr+aqzDhtwrovK4vEhnz8groYxC3+PeYdqMjW+0mU9P2wgqZt35Lm3WLT0EYw2cZ6HbE+0AlnQtmt57MaT99Aryk+rCGNMekqYsC1kFo084HvYuZvpAgIyNhKXNghMYtRkM8SXO2x9BOMoNdprDXR2NdYxn1+rAgvBd7jBnbec6YvBi+6tPyONANVzY1cvdyUvznzxF5LEpbUrBM3tV6uZhMDMOduDJD5Tytsb5LTY4wfCswoLZxf3ZIQ6Yrv7p9DrmLeIxph6AP4uj9elLzr6aKqN2Sp3CIaTTfE7d2lHjlLWpaeBLxcGd+fR1NOPI+R3KwKvhKmlCT7icCeeN3iiv6Hwp4v4+Qnhq1cWGpgw9UmBqLXK4MtlSLIhL93Zm2SiXhYWPGFrwdzQj3na515kSAMvxo5xn0kR/8dR3kUhiJCd4yju44NM2Qy/1/Xz09gXGUA5YeEB5cUSR6CtyMR2n0AGDzzPZqpJu9EVlCaBSK3VRPa8zSkQGwovrB2BBZrDvyFFkxSfuzZuKjfn/ueiyBWH/WD6sZa8XxdNwvi+YEHyFaDPFir/tLz/TWQm1xkqs/1ilUWUPcnQ/zOeJpAsqU7ssM=
  bucket: hardback
  acl: private
  on:
    repo: alanpoon/hardback_conrod
