# Node.js Express Web App to Linux on Azure
# Build a Node.js Express app and deploy it to Azure as a Linux web app.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

variables:

  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: '2dfae9d3-52f0-402c-be7b-8870f6bb38ff'
  
  # Web app name
  webAppName: 'hardback'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    container: rustropy/crayon:version1.0
      
    steps:
    - script: |
        echo $PATH
      displayName: 'crayon-cli which'
    - script: |
        crayon-cli  --version
      displayName: 'crayon-cli verison'
    - script: |
        which crayon-cli
      displayName: 'which crayon-cli'
    - script: |
        ls -l .
      displayName: 'ls this directory'
    - script: |
        whoami
      displayName: 'whoami'
    - script: |
        RUST_BACKTRACE=1 crayon-cli build
      displayName: 'crayon-cli'
    - script: |
        cd tools/wasm-template && npm install
      displayName: 'npm install, build and test'
    - script: |
        cd tools/wasm-template && ./run.sh
      displayName: 'build wasm'

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/tools/wasm-template'
        includeRootFolder: true
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - task: PublishPipelineArtifact@0
      displayName: 'Publish pipeline artifacts'
      inputs:
        targetPath: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: 'development'
    pool: 
      vmImage: $(vmImageName)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@1
            displayName: 'Download Pipeline Artifact'
            inputs:
              buildType: 'current'
            
          - task: AzureWebApp@1
            displayName: 'Azure Web App Deploy: '
            inputs:
              azureSubscription: $(azureSubscription)
              appType: webAppLinux
              appName: $(webAppName)
              runtimeStack: 'NODE|10.10'
              package: $(System.ArtifactsDirectory)/drop/$(Build.BuildId).zip
              startUpCommand: 'npm run serve'