[package]
name = "hardback_conrod"
version = "0.1.0"
authors = ["alanpoon"]

[dependencies]
conrod = { version ="0.56", features = ["glium","winit"]}
conrod_derive = "0.1.0"
conrod_chat = {path ="../conrod_chat", features=["default"]}
conrod_keypad ={path ="../conrod_keypad"}
futures ={ version = "0.1.14", features=["use_std"] }
cardgame_widgets = {path ="../cardgame_widgets"}
cardgame_macros = {path="../cardgame_macros"}
hardback_meta = {path = "../hardback_meta"}
hardback_codec = {path = "../hardback_codec"}
websocket = { version ="0.20.2",optional = true}
tokio-core ="0.1.9"
serde_json = "1.0"
glium = { version = "0.17"}
shared_library = "0.1.7"
image = "0.15.0"
find_folder = "0.3.0"
toa-ping ={path="../toa-ping"}


[features]
_ws = ["websocket"]
backend_glium_winit = []
default = ["backend_glium_winit","_ws"]

[dev-dependencies]
image = "0.15.0"
find_folder = "0.3.0"

[lib]
name = "hardback_conrod"
path = "src/lib.rs"

[[bin]]
name = "hardback"
path = "src/bin/main.rs"