[package]
name = "hardback_conrod"
version = "0.1.0"
authors = ["alanpoon"]

[dependencies]
conrod = { version ="0.54", features = ["glium","winit"]}
conrod_derive = "0.1.0"
futures ={ version = "0.1.14", features=["use_std"] }
cardgame_widgets = {path ="../cardgame_widgets"}
websocket = { version ="0.20.2",optional = true}
tokio-core ="0.1.9"
serde="1.0"
serde_json = "1.0"
serde_derive ="1.0"
glium = { version = "0.17"}
shared_library = "0.1.7"

[features]
_ws = ["websocket"]
backend_glium_winit = []
default = ["backend_glium_winit","_ws"]

[dev-dependencies]
image = "0.15.0"
find_folder = "0.3.0"


[lib]
name = "hardback_conrod"
path = "src/lib.rs"
