--- 
jobs: 
  build: 
    docker: 
      - 
        image: tomaka/cargo-apk
    steps: 
      - checkout
      - 
        run: "rustup show"
      - 
        run: "rustup target add armv7-linux-androideabi"
      - 
        run: "apt-get -y install python"
      - 
        run: "wget http://www.openssl.org/source/openssl-1.0.2l.tar.gz"
      - 
        run: "tar -xvzf openssl-1.0.2l.tar.gz"
      - 
        run: "cp ssl_for_android.sh openssl-1.0.2l"
      - 
        run: "cd /openssl-1.0.2l"
      -
        run: "pwd"
      - 
        run: "ls"
      - 
        run: "sh ssl_for_android.sh --verbose"
      - 
        run: "cd .."
      - 
        run: "git clone --depth=1 https://github.com/alanpoon/cargo-edit cargo-edit"
      - 
        run: "cargo install --path cargo-edit"
      - 
        run: "cargo add https://github.com/alanpoon/conrod_chat --features \"keypad\""
      - 
        run: "cargo apk run --features android"
  deploy: 
    docker: 
      - 
        image: tomaka/cargo-apk
    steps: 
      - checkout
      - 
        run: "rustup show"
      - 
        run: "rustup target add armv7-linux-androideabi"
      - 
        run: "git clone --depth=1 https://github.com/alanpoon/cargo-edit cargo-edit"
      - 
        run: "cargo install --path cargo-edit"
      - 
        run: "cargo rm conrod_chat"
      - 
        run: "cargo add https://github.com/alanpoon/conrod_chat --features \"keypad\""
      - 
        run: "cargo apk run --features android --release"
      - 
        run: ./.circleci/upload_apk_to_github_releases.sh
version: 2
workflows: 
  build-and-deploy: 
    jobs: 
      - 
        build: 
          filters: 
            tags: 
              ignore: /.*/
      - 
        deploy: 
          filters: 
            branches: 
              ignore: /.*/
            tags: 
              only: /.*/
  version: 2