--- 
jobs: 
  build: 
    docker: 
      - 
        environment: 
          ANDROID_PLATFORM: android-18
        image: tomaka/cargo-apk
    steps: 
      - checkout
      - 
        run: "rustup show"
      - 
        run: "rustup target add armv7-linux-androideabi"
      - 
        run: "apt-get install libssl-dev"
      - 
        run: "git clone --depth=1 https://github.com/alanpoon/cargo-edit cargo-edit"
      - 
        run: "cargo install --path cargo-edit"
      - 
        run: "cargo add https://github.com/alanpoon/conrod_chat --features \"keypad\""
      - 
        run: "apt-get -y install python-pip"
      - 
        run: "pip -V"
      - 
        run: "pip install --upgrade pip"        
      - 
        run: "wget http://www.openssl.org/source/openssl-1.0.2l.tar.gz"
      - 
        run: "tar -xvzf openssl-1.0.2l.tar.gz"
      - 
        run: "cp ssl_for_android.sh openssl-1.0.2l"
      - 
        run: 
          command: "cd openssl-1.0.2l && pwd && sh ssl_for_android.sh && ls /usr/local/ssl/${ANDROID_PLATFORM}"
          environment: 
            OPENSSL_DIR: "/usr/local/ssl/${ANDROID_PLATFORM}/armeabi-v7a"
            OPENSSL_LIB_DIR: "/usr/local/ssl/${ANDROID_PLATFORM}/armeabi-v7a/lib"
          name: ssl_for_android
      - 
        run: 
          command: "cargo apk build --release --features android --no-default-features"
          environment: 
            OPENSSL_DIR: /usr/local/ssl/android-18/armeabi-v7a
            OPENSSL_LIB_DIR: /usr/local/ssl/android-18/armeabi-v7a/lib
          name: "apk build"
      - 
        run: "pip install awscli --upgrade --user"
      - 
        run: "ls target/android-artifacts/app/build/outputs/apk"
      -
        run: "chmod +x ~/.local/bin/aws"    
      -
        run: "~/.local/bin/aws --version"
      - 
        run: 
          command: "~/.local/bin/aws s3 sync target/android-artifacts/app/build/outputs/apk/app-release-unsigned.apk s3://hardback --delete --region ap-southeast-1"
          name: "Deploy to S3"
version: 2
workflows: 
  build-and-deploy: 
    jobs: 
      - 
        build: 
          filters: 
            tags: 
              ignore: /.*/
  version: 2