version: 2

jobs:
  build:
    docker:
      - image: tomaka/cargo-apk
    steps:
      - checkout
      - run: rustup show
      - run: git clone --depth=1 https://github.com/alanpoon/cargo-edit cargo-edit
      - run: cargo install --path cargo-edit
      - run: cargo add https://github.com/alanpoon/conrod_chat --target cfg(android) --features "keypad"
      - run: cargo apk run --features android

  deploy:
    docker:
      - image: tomaka/cargo-apk
    steps:
      - checkout
      - run: rustup show
      - run: git clone --depth=1 https://github.com/alanpoon/cargo-edit cargo-edit
      - run: cargo install --path cargo-edit
      - run: cargo rm conrod_chat
      - run: cargo add https://github.com/alanpoon/conrod_chat --features "keypad"
      - run: cargo apk run --features android
      - run: ./.circleci/upload_apk_to_github_releases.sh

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              ignore: /.*/
      - deploy:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
