version: 2

jobs:
  build:
    docker:
      - image: tomaka/cargo-apk
    steps:
      - checkout
      - run: rustup show
      - run: cargo apk build

  deploy:
    docker:
      - image: tomaka/cargo-apk
    steps:
      - run: rustup show
      - run: mkdir workspace/hardback_conrod
      - run: cd workspace/hardback_conrod
      - checkout
      - run: git clone --depth=1 https://github.com/alanpoon/cardgame_widgets ../cardgame_widgets
      - run: git clone --depth=1 https://github.com/alanpoon/cardgame_macros ../cardgame_macros
      - run: git clone --depth=1 https://github.com/alanpoon/hardback_meta ../hardback_meta
      - run: git clone --depth=1 https://github.com/alanpoon/hardback_codec ../hardback_codec
      - run: cargo apk build
      - run: ./.circleci/upload_apk_to_github_releases.sh

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              ignore: /.*/
      - deploy:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
